# Generated by Django 4.2.17 on 2024-12-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='remuneração',
            new_name='remuneracao',
        ),
    ]
